# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0003_alter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='can_be_used_for_non_products',
            field=models.BooleanField(default=True, help_text='Whether this account can be used to pay for shipping and other charges'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Open', max_length=32),
        ),
    ]
